version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build TypeScript
          command: npm run build

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
