version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3

      - run:
          name: Run tests
          command: |
            bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - feature/ruby
