version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.21.5
    working_directory: /go/src/github.com/your-username/your-repo-name
    steps:
      - checkout

      - run:
          name: Run Tests
          command: go test ./...

workflows:
  version: 2
  build:
    jobs:
      - build
