version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build Project
          command: dotnet build

      - run:
          name: Run Tests
          command: dotnet test

workflows:
  version: 2
  build:
    jobs:
      - build
